// US States data with ballot initiative info
export interface StateData {
  slug: string;
  name: string;
  abbr: string;
  signatureTarget: number;
  populationPercent: string;
  hasBallotInitiative: boolean;
  hasOrganizer: boolean;
  campaignStatus: 'active' | 'coming-soon' | 'not-yet';
  seniorSenator: {
    name: string;
    party: string;
    phone: string;
    website: string;
  };
  juniorSenator: {
    name: string;
    party: string;
    phone: string;
    website: string;
  };
  representatives: Array<{
    name: string;
    district: number;
    party: string;
    phone: string;
  }>;
}

export const STATES: StateData[] = [
  {
    slug: 'alabama',
    name: 'Alabama',
    abbr: 'AL',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Tommy Tuberville', party: 'R', phone: '(202) 224-4124', website: 'tuberville.senate.gov' },
    juniorSenator: { name: 'Katie Britt', party: 'R', phone: '(202) 224-5744', website: 'britt.senate.gov' },
    representatives: [],
  },
  {
    slug: 'alaska',
    name: 'Alaska',
    abbr: 'AK',
    signatureTarget: 30000,
    populationPercent: '~10% of votes cast',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Lisa Murkowski', party: 'R', phone: '(202) 224-6665', website: 'murkowski.senate.gov' },
    juniorSenator: { name: 'Dan Sullivan', party: 'R', phone: '(202) 224-3004', website: 'sullivan.senate.gov' },
    representatives: [],
  },
  {
    slug: 'arizona',
    name: 'Arizona',
    abbr: 'AZ',
    signatureTarget: 238000,
    populationPercent: '10% of qualified electors',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Mark Kelly', party: 'D', phone: '(202) 224-2235', website: 'kelly.senate.gov' },
    juniorSenator: { name: 'Ruben Gallego', party: 'D', phone: '(202) 224-4521', website: 'gallego.senate.gov' },
    representatives: [],
  },
  {
    slug: 'arkansas',
    name: 'Arkansas',
    abbr: 'AR',
    signatureTarget: 78000,
    populationPercent: '8% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'John Boozman', party: 'R', phone: '(202) 224-4843', website: 'boozman.senate.gov' },
    juniorSenator: { name: 'Tom Cotton', party: 'R', phone: '(202) 224-2353', website: 'cotton.senate.gov' },
    representatives: [],
  },
  {
    slug: 'california',
    name: 'California',
    abbr: 'CA',
    signatureTarget: 546651,
    populationPercent: '5% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: true,
    campaignStatus: 'active',
    seniorSenator: { name: 'Alex Padilla', party: 'D', phone: '(202) 224-3553', website: 'padilla.senate.gov' },
    juniorSenator: { name: 'Adam Schiff', party: 'D', phone: '(202) 224-3841', website: 'schiff.senate.gov' },
    representatives: [],
  },
  {
    slug: 'colorado',
    name: 'Colorado',
    abbr: 'CO',
    signatureTarget: 124632,
    populationPercent: '5% of votes cast for Sec. of State',
    hasBallotInitiative: true,
    hasOrganizer: true,
    campaignStatus: 'active',
    seniorSenator: { name: 'Michael Bennet', party: 'D', phone: '(202) 224-5852', website: 'bennet.senate.gov' },
    juniorSenator: { name: 'John Hickenlooper', party: 'D', phone: '(202) 224-5941', website: 'hickenlooper.senate.gov' },
    representatives: [],
  },
  {
    slug: 'connecticut',
    name: 'Connecticut',
    abbr: 'CT',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Richard Blumenthal', party: 'D', phone: '(202) 224-2823', website: 'blumenthal.senate.gov' },
    juniorSenator: { name: 'Chris Murphy', party: 'D', phone: '(202) 224-4041', website: 'murphy.senate.gov' },
    representatives: [],
  },
  {
    slug: 'delaware',
    name: 'Delaware',
    abbr: 'DE',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Chris Coons', party: 'D', phone: '(202) 224-5042', website: 'coons.senate.gov' },
    juniorSenator: { name: 'Lisa Blunt Rochester', party: 'D', phone: '(202) 224-2441', website: 'bluntrochester.senate.gov' },
    representatives: [],
  },
  {
    slug: 'florida',
    name: 'Florida',
    abbr: 'FL',
    signatureTarget: 891589,
    populationPercent: '8% of votes cast in presidential election',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Rick Scott', party: 'R', phone: '(202) 224-5274', website: 'rickscott.senate.gov' },
    juniorSenator: { name: 'Ashley Moody', party: 'R', phone: '(202) 224-3041', website: 'moody.senate.gov' },
    representatives: [],
  },
  {
    slug: 'georgia',
    name: 'Georgia',
    abbr: 'GA',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Jon Ossoff', party: 'D', phone: '(202) 224-3521', website: 'ossoff.senate.gov' },
    juniorSenator: { name: 'Raphael Warnock', party: 'D', phone: '(202) 224-3643', website: 'warnock.senate.gov' },
    representatives: [],
  },
  {
    slug: 'hawaii',
    name: 'Hawaii',
    abbr: 'HI',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Mazie Hirono', party: 'D', phone: '(202) 224-6361', website: 'hirono.senate.gov' },
    juniorSenator: { name: 'Brian Schatz', party: 'D', phone: '(202) 224-3934', website: 'schatz.senate.gov' },
    representatives: [],
  },
  {
    slug: 'idaho',
    name: 'Idaho',
    abbr: 'ID',
    signatureTarget: 67000,
    populationPercent: '6% of registered voters',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Mike Crapo', party: 'R', phone: '(202) 224-6142', website: 'crapo.senate.gov' },
    juniorSenator: { name: 'Jim Risch', party: 'R', phone: '(202) 224-2752', website: 'risch.senate.gov' },
    representatives: [],
  },
  {
    slug: 'illinois',
    name: 'Illinois',
    abbr: 'IL',
    signatureTarget: 290000,
    populationPercent: '8% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Dick Durbin', party: 'D', phone: '(202) 224-2152', website: 'durbin.senate.gov' },
    juniorSenator: { name: 'Tammy Duckworth', party: 'D', phone: '(202) 224-2854', website: 'duckworth.senate.gov' },
    representatives: [],
  },
  {
    slug: 'indiana',
    name: 'Indiana',
    abbr: 'IN',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Todd Young', party: 'R', phone: '(202) 224-5623', website: 'young.senate.gov' },
    juniorSenator: { name: 'Jim Banks', party: 'R', phone: '(202) 224-5623', website: 'banks.senate.gov' },
    representatives: [],
  },
  {
    slug: 'iowa',
    name: 'Iowa',
    abbr: 'IA',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Chuck Grassley', party: 'R', phone: '(202) 224-3744', website: 'grassley.senate.gov' },
    juniorSenator: { name: 'Joni Ernst', party: 'R', phone: '(202) 224-3254', website: 'ernst.senate.gov' },
    representatives: [],
  },
  {
    slug: 'kansas',
    name: 'Kansas',
    abbr: 'KS',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Jerry Moran', party: 'R', phone: '(202) 224-6521', website: 'moran.senate.gov' },
    juniorSenator: { name: 'Roger Marshall', party: 'R', phone: '(202) 224-4774', website: 'marshall.senate.gov' },
    representatives: [],
  },
  {
    slug: 'kentucky',
    name: 'Kentucky',
    abbr: 'KY',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Mitch McConnell', party: 'R', phone: '(202) 224-2541', website: 'mcconnell.senate.gov' },
    juniorSenator: { name: 'Rand Paul', party: 'R', phone: '(202) 224-4343', website: 'paul.senate.gov' },
    representatives: [],
  },
  {
    slug: 'louisiana',
    name: 'Louisiana',
    abbr: 'LA',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Bill Cassidy', party: 'R', phone: '(202) 224-5824', website: 'cassidy.senate.gov' },
    juniorSenator: { name: 'John Kennedy', party: 'R', phone: '(202) 224-4623', website: 'kennedy.senate.gov' },
    representatives: [],
  },
  {
    slug: 'maine',
    name: 'Maine',
    abbr: 'ME',
    signatureTarget: 67000,
    populationPercent: '~10% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Susan Collins', party: 'R', phone: '(202) 224-2523', website: 'collins.senate.gov' },
    juniorSenator: { name: 'Angus King', party: 'I', phone: '(202) 224-5344', website: 'king.senate.gov' },
    representatives: [],
  },
  {
    slug: 'maryland',
    name: 'Maryland',
    abbr: 'MD',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Chris Van Hollen', party: 'D', phone: '(202) 224-4654', website: 'vanhollen.senate.gov' },
    juniorSenator: { name: 'Angela Alsobrooks', party: 'D', phone: '(202) 224-4524', website: 'alsobrooks.senate.gov' },
    representatives: [],
  },
  {
    slug: 'massachusetts',
    name: 'Massachusetts',
    abbr: 'MA',
    signatureTarget: 69821,
    populationPercent: '~3.5% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'coming-soon',
    seniorSenator: { name: 'Elizabeth Warren', party: 'D', phone: '(202) 224-4543', website: 'warren.senate.gov' },
    juniorSenator: { name: 'Ed Markey', party: 'D', phone: '(202) 224-2742', website: 'markey.senate.gov' },
    representatives: [],
  },
  {
    slug: 'michigan',
    name: 'Michigan',
    abbr: 'MI',
    signatureTarget: 340000,
    populationPercent: '8% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Gary Peters', party: 'D', phone: '(202) 224-6221', website: 'peters.senate.gov' },
    juniorSenator: { name: 'Elissa Slotkin', party: 'D', phone: '(202) 224-4822', website: 'slotkin.senate.gov' },
    representatives: [],
  },
  {
    slug: 'minnesota',
    name: 'Minnesota',
    abbr: 'MN',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Amy Klobuchar', party: 'D', phone: '(202) 224-3244', website: 'klobuchar.senate.gov' },
    juniorSenator: { name: 'Tina Smith', party: 'D', phone: '(202) 224-5641', website: 'smith.senate.gov' },
    representatives: [],
  },
  {
    slug: 'mississippi',
    name: 'Mississippi',
    abbr: 'MS',
    signatureTarget: 106000,
    populationPercent: '12% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Roger Wicker', party: 'R', phone: '(202) 224-6253', website: 'wicker.senate.gov' },
    juniorSenator: { name: 'Cindy Hyde-Smith', party: 'R', phone: '(202) 224-5054', website: 'hydesmith.senate.gov' },
    representatives: [],
  },
  {
    slug: 'missouri',
    name: 'Missouri',
    abbr: 'MO',
    signatureTarget: 160000,
    populationPercent: '5% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Josh Hawley', party: 'R', phone: '(202) 224-6154', website: 'hawley.senate.gov' },
    juniorSenator: { name: 'Eric Schmitt', party: 'R', phone: '(202) 224-5721', website: 'schmitt.senate.gov' },
    representatives: [],
  },
  {
    slug: 'montana',
    name: 'Montana',
    abbr: 'MT',
    signatureTarget: 30000,
    populationPercent: '5% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Steve Daines', party: 'R', phone: '(202) 224-2651', website: 'daines.senate.gov' },
    juniorSenator: { name: 'Tim Sheehy', party: 'R', phone: '(202) 224-2644', website: 'sheehy.senate.gov' },
    representatives: [],
  },
  {
    slug: 'nebraska',
    name: 'Nebraska',
    abbr: 'NE',
    signatureTarget: 87000,
    populationPercent: '7% of registered voters',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Deb Fischer', party: 'R', phone: '(202) 224-6551', website: 'fischer.senate.gov' },
    juniorSenator: { name: 'Pete Ricketts', party: 'R', phone: '(202) 224-4224', website: 'ricketts.senate.gov' },
    representatives: [],
  },
  {
    slug: 'nevada',
    name: 'Nevada',
    abbr: 'NV',
    signatureTarget: 100000,
    populationPercent: '10% of votes cast',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Catherine Cortez Masto', party: 'D', phone: '(202) 224-3542', website: 'cortezmasto.senate.gov' },
    juniorSenator: { name: 'Jacky Rosen', party: 'D', phone: '(202) 224-6244', website: 'rosen.senate.gov' },
    representatives: [],
  },
  {
    slug: 'new-hampshire',
    name: 'New Hampshire',
    abbr: 'NH',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Jeanne Shaheen', party: 'D', phone: '(202) 224-2841', website: 'shaheen.senate.gov' },
    juniorSenator: { name: 'Maggie Hassan', party: 'D', phone: '(202) 224-3324', website: 'hassan.senate.gov' },
    representatives: [],
  },
  {
    slug: 'new-jersey',
    name: 'New Jersey',
    abbr: 'NJ',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Cory Booker', party: 'D', phone: '(202) 224-3224', website: 'booker.senate.gov' },
    juniorSenator: { name: 'Andy Kim', party: 'D', phone: '(202) 224-4744', website: 'kim.senate.gov' },
    representatives: [],
  },
  {
    slug: 'new-mexico',
    name: 'New Mexico',
    abbr: 'NM',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Martin Heinrich', party: 'D', phone: '(202) 224-5521', website: 'heinrich.senate.gov' },
    juniorSenator: { name: 'Ben Ray Lujan', party: 'D', phone: '(202) 224-6621', website: 'lujan.senate.gov' },
    representatives: [],
  },
  {
    slug: 'new-york',
    name: 'New York',
    abbr: 'NY',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Chuck Schumer', party: 'D', phone: '(202) 224-6542', website: 'schumer.senate.gov' },
    juniorSenator: { name: 'Kirsten Gillibrand', party: 'D', phone: '(202) 224-4451', website: 'gillibrand.senate.gov' },
    representatives: [],
  },
  {
    slug: 'north-carolina',
    name: 'North Carolina',
    abbr: 'NC',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Thom Tillis', party: 'R', phone: '(202) 224-6342', website: 'tillis.senate.gov' },
    juniorSenator: { name: 'Ted Budd', party: 'R', phone: '(202) 224-3154', website: 'budd.senate.gov' },
    representatives: [],
  },
  {
    slug: 'north-dakota',
    name: 'North Dakota',
    abbr: 'ND',
    signatureTarget: 16000,
    populationPercent: '2% of resident population',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'John Hoeven', party: 'R', phone: '(202) 224-2551', website: 'hoeven.senate.gov' },
    juniorSenator: { name: 'Kevin Cramer', party: 'R', phone: '(202) 224-2043', website: 'cramer.senate.gov' },
    representatives: [],
  },
  {
    slug: 'ohio',
    name: 'Ohio',
    abbr: 'OH',
    signatureTarget: 132000,
    populationPercent: '3% of votes cast for governor (statutory)',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Jon Husted', party: 'R', phone: '(202) 224-2315', website: 'husted.senate.gov' },
    juniorSenator: { name: 'Bernie Moreno', party: 'R', phone: '(202) 224-2315', website: 'moreno.senate.gov' },
    representatives: [],
  },
  {
    slug: 'oklahoma',
    name: 'Oklahoma',
    abbr: 'OK',
    signatureTarget: 95000,
    populationPercent: '8% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'James Lankford', party: 'R', phone: '(202) 224-5754', website: 'lankford.senate.gov' },
    juniorSenator: { name: 'Markwayne Mullin', party: 'R', phone: '(202) 224-4721', website: 'mullin.senate.gov' },
    representatives: [],
  },
  {
    slug: 'oregon',
    name: 'Oregon',
    abbr: 'OR',
    signatureTarget: 61275,
    populationPercent: '6% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'coming-soon',
    seniorSenator: { name: 'Ron Wyden', party: 'D', phone: '(202) 224-5244', website: 'wyden.senate.gov' },
    juniorSenator: { name: 'Jeff Merkley', party: 'D', phone: '(202) 224-3753', website: 'merkley.senate.gov' },
    representatives: [],
  },
  {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    abbr: 'PA',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'John Fetterman', party: 'D', phone: '(202) 224-4254', website: 'fetterman.senate.gov' },
    juniorSenator: { name: 'Dave McCormick', party: 'R', phone: '(202) 224-6324', website: 'mccormick.senate.gov' },
    representatives: [],
  },
  {
    slug: 'rhode-island',
    name: 'Rhode Island',
    abbr: 'RI',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Jack Reed', party: 'D', phone: '(202) 224-4642', website: 'reed.senate.gov' },
    juniorSenator: { name: 'Sheldon Whitehouse', party: 'D', phone: '(202) 224-2921', website: 'whitehouse.senate.gov' },
    representatives: [],
  },
  {
    slug: 'south-carolina',
    name: 'South Carolina',
    abbr: 'SC',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Lindsey Graham', party: 'R', phone: '(202) 224-5972', website: 'lgraham.senate.gov' },
    juniorSenator: { name: 'Tim Scott', party: 'R', phone: '(202) 224-6121', website: 'scott.senate.gov' },
    representatives: [],
  },
  {
    slug: 'south-dakota',
    name: 'South Dakota',
    abbr: 'SD',
    signatureTarget: 17000,
    populationPercent: '5% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'John Thune', party: 'R', phone: '(202) 224-2321', website: 'thune.senate.gov' },
    juniorSenator: { name: 'Mike Rounds', party: 'R', phone: '(202) 224-5842', website: 'rounds.senate.gov' },
    representatives: [],
  },
  {
    slug: 'tennessee',
    name: 'Tennessee',
    abbr: 'TN',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Marsha Blackburn', party: 'R', phone: '(202) 224-3344', website: 'blackburn.senate.gov' },
    juniorSenator: { name: 'Bill Hagerty', party: 'R', phone: '(202) 224-4944', website: 'hagerty.senate.gov' },
    representatives: [],
  },
  {
    slug: 'texas',
    name: 'Texas',
    abbr: 'TX',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'John Cornyn', party: 'R', phone: '(202) 224-2934', website: 'cornyn.senate.gov' },
    juniorSenator: { name: 'Ted Cruz', party: 'R', phone: '(202) 224-5922', website: 'cruz.senate.gov' },
    representatives: [],
  },
  {
    slug: 'utah',
    name: 'Utah',
    abbr: 'UT',
    signatureTarget: 116000,
    populationPercent: '6% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Mike Lee', party: 'R', phone: '(202) 224-5444', website: 'lee.senate.gov' },
    juniorSenator: { name: 'John Curtis', party: 'R', phone: '(202) 224-5251', website: 'curtis.senate.gov' },
    representatives: [],
  },
  {
    slug: 'vermont',
    name: 'Vermont',
    abbr: 'VT',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Bernie Sanders', party: 'I', phone: '(202) 224-5141', website: 'sanders.senate.gov' },
    juniorSenator: { name: 'Peter Welch', party: 'D', phone: '(202) 224-4242', website: 'welch.senate.gov' },
    representatives: [],
  },
  {
    slug: 'virginia',
    name: 'Virginia',
    abbr: 'VA',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Mark Warner', party: 'D', phone: '(202) 224-2023', website: 'warner.senate.gov' },
    juniorSenator: { name: 'Tim Kaine', party: 'D', phone: '(202) 224-4024', website: 'kaine.senate.gov' },
    representatives: [],
  },
  {
    slug: 'washington',
    name: 'Washington',
    abbr: 'WA',
    signatureTarget: 324516,
    populationPercent: '8% of votes cast for governor',
    hasBallotInitiative: true,
    hasOrganizer: true,
    campaignStatus: 'active',
    seniorSenator: { name: 'Patty Murray', party: 'D', phone: '(202) 224-2621', website: 'murray.senate.gov' },
    juniorSenator: { name: 'Maria Cantwell', party: 'D', phone: '(202) 224-3441', website: 'cantwell.senate.gov' },
    representatives: [],
  },
  {
    slug: 'west-virginia',
    name: 'West Virginia',
    abbr: 'WV',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Shelley Moore Capito', party: 'R', phone: '(202) 224-6472', website: 'capito.senate.gov' },
    juniorSenator: { name: 'Jim Justice', party: 'R', phone: '(202) 224-3954', website: 'justice.senate.gov' },
    representatives: [],
  },
  {
    slug: 'wisconsin',
    name: 'Wisconsin',
    abbr: 'WI',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'Ron Johnson', party: 'R', phone: '(202) 224-5323', website: 'ronjohnson.senate.gov' },
    juniorSenator: { name: 'Eric Hovde', party: 'R', phone: '(202) 224-5653', website: 'hovde.senate.gov' },
    representatives: [],
  },
  {
    slug: 'wyoming',
    name: 'Wyoming',
    abbr: 'WY',
    signatureTarget: 42000,
    populationPercent: '15% of votes cast',
    hasBallotInitiative: true,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'John Barrasso', party: 'R', phone: '(202) 224-6441', website: 'barrasso.senate.gov' },
    juniorSenator: { name: 'Cynthia Lummis', party: 'R', phone: '(202) 224-3424', website: 'lummis.senate.gov' },
    representatives: [],
  },
  // DC - not a state but included for the map
  {
    slug: 'dc',
    name: 'District of Columbia',
    abbr: 'DC',
    signatureTarget: 0,
    populationPercent: 'N/A',
    hasBallotInitiative: false,
    hasOrganizer: false,
    campaignStatus: 'not-yet',
    seniorSenator: { name: 'N/A (no Senate representation)', party: '', phone: '', website: '' },
    juniorSenator: { name: 'N/A (no Senate representation)', party: '', phone: '', website: '' },
    representatives: [],
  },
];

export function getStateBySlug(slug: string): StateData | undefined {
  return STATES.find(s => s.slug === slug);
}

export function getStateByAbbr(abbr: string): StateData | undefined {
  return STATES.find(s => s.abbr === abbr);
}

export function getActiveStates(): StateData[] {
  return STATES.filter(s => s.campaignStatus === 'active');
}

export function getComingSoonStates(): StateData[] {
  return STATES.filter(s => s.campaignStatus === 'coming-soon');
}

export function getBallotInitiativeStates(): StateData[] {
  return STATES.filter(s => s.hasBallotInitiative);
}
